# Generated by Django 2.2 on 2019-04-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='business',
            field=models.CharField(choices=[('food_truck', 'Food Truck'), ('construction', 'Construction'), ('others', 'Others')], max_length=100),
        ),
    ]
